site_name: Magic City DevOps
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: lime

nav:
  - Blog:
    - blog/index.md
  - Homelab:
    - Ubuntu Server Homelab Configuration Guide: homelab/ubuntu-server-homelab-configuration-guide.md
    - Openstack Configuration Guide: homelab/openstack-configuration-guide.md
    - GitOps with istio and ArgoCD: homelab/gitops-with-istio-and-argocd.md
    - Kubernetes Gateway API with Istio: homelab/k8s-gateway-api-with-istio.md


plugins:
  - social
  - glightbox
  - blog

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jonathanelbailey
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jonathanedwardleebailey/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/jonathanelbailey"  target="_blank" rel="noopener">Jonathan Bailey</a>